services:
    pgdatabase:
        image: postgres:13
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=ny_taxi
        volumes:
            - "c:/Users/AbdulHafez/data-engineering-camp/Week_1_Basics_And_Setups/docker-sql/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
        ports:
            - "5432:5432"
        networks:
            - airflow

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        volumes:
            - "./data_pgadmin:/var/lib/pgadmin"
        ports:
            - "8088:80"
        networks:
            - airflow

networks:
    airflow:
        external:
            name: airflow_default